# Sample .travis.yml for R projects.
#
# See README.md for instructions, or for more configuration options,
# see the wiki:
#   https://github.com/craigcitro/r-travis/wiki

####language: c
#####sudo: required
# Sample .travis.yml for R projects.
#
# See README.md for instructions, or for more configuration options,
# see the wiki:
#   https://github.com/craigcitro/r-travis/wiki

language: r
dist: trusty
cache: packages
sudo: false

r: 3.5.1

r_packages:
  - covr
  - devtools
  - testthat

bioc_packages:
  - GenomicRanges

r_github_packages:
  - mskilab/gUtils

before_install:
    - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
    - chmod 755 ./travis-tool.sh

script:
  - ./travis-tool.sh run_tests

after_failure:
  - ./travis-tool.sh dump_logs

after_success:
  - travis_wait Rscript -e 'covr::codecov()'


notifications:
  email:
      on_success: change
      on_failure: change
